apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "cm9ib3Nob3A="
  AMQP_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  replicas: 2
  matchLabels:
    selector:
      project: roboshop
      tier: backend
      component: roboshop
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: roboshop
    spec:
      containers:
        - name: payment
          image: sravankumar152/payment:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "150m"
              memory: "70Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: payment

---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  selector:
    project: roboshop
    tier: backend
    component: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


          
    