apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3AK"
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjMK"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: rabbitmq
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: sravankumar152/rabbitmq:3
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "300m"
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: rabbitmq
spec:
  selector:
    project: roboshop
    tier: backend
    component: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672